/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Halaman;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;



/**
 *
 * @author str5
 */
public class loginadmin extends javax.swing.JFrame {
    
    private Connection connect;
    private String driveName = "com.mysql.jdbc.Driver";
    private String url = "jdbc:mysql://localhost/artaTravel?serverTimezone=UTC";
    private String username = "root";
    private String password = "";

    /**
     * Creates new form loginadmin
     */
    public loginadmin() {
        initComponents();
        this.setLocationRelativeTo(null);
        usernm.setBackground(new Color(0, 0, 0, 0));
        pw.setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pw = new javax.swing.JPasswordField();
        bt_close = new javax.swing.JLabel();
        usernm = new javax.swing.JTextField();
        signin = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        home = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pw.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 270, 40));

        bt_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_closeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_closeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_closeMouseEntered(evt);
            }
        });
        getContentPane().add(bt_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 60, 40));

        usernm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        usernm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernmActionPerformed(evt);
            }
        });
        getContentPane().add(usernm, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 270, 30));

        signin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signinMouseClicked(evt);
            }
        });
        getContentPane().add(signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 270, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Halaman/gambar/day1-login-form.jpg"))); // NOI18N
        background.setLabelFor(background);
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 60, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernmActionPerformed

    private void bt_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_closeMouseClicked
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_bt_closeMouseClicked

    private void bt_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_closeMouseExited
        ImageIcon L = new ImageIcon(getClass().getResource("gambar/day1-login-form.jpg"));
        background.setIcon(L);
    }//GEN-LAST:event_bt_closeMouseExited

    private void bt_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_closeMouseEntered
        ImageIcon L = new ImageIcon(getClass().getResource("gambar/adminclose.jpg"));
        background.setIcon(L);
    }//GEN-LAST:event_bt_closeMouseEntered

    private void signinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinMouseClicked
        
        String user = usernm.getText();
        String pass = pw.getText();
        try {
            
            PreparedStatement psmt = getConn2().prepareStatement(""
                    + "select * from login WHERE user=? AND pass=?");
            psmt.setString(1, user);
            psmt.setString(2, pass);

            ResultSet resultSet = psmt.executeQuery();
            if (resultSet.next() == true) {
                this.dispose();
                menu_admin L = new menu_admin();
                L.setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "Gagal Login");

            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_signinMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        halaman_menu T = new halaman_menu();
        T.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_homeMouseClicked

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        ImageIcon L = new ImageIcon(getClass().getResource("gambar/day1-login-form.jpg"));
        background.setIcon(L);
    }//GEN-LAST:event_homeMouseExited

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        ImageIcon L = new ImageIcon(getClass().getResource("gambar/adminclose.jpg"));
        background.setIcon(L);
    }//GEN-LAST:event_homeMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginadmin().setVisible(true);
            }
        });
    }
     public Connection getConn2() throws SQLException 
    {
        if (connect == null) 
        { 
            try 
            {
                Class.forName(driveName);
                try 
                {
                    connect = DriverManager.getConnection(url, username, password);
                } catch (SQLException se) {
                    System.out.println("Koneksi gagal!");
                    System.out.println(se);
                    System.exit(0);
                }
            } catch (ClassNotFoundException se) {
                System.out.println("Class tidak ditemukan");
                System.exit(0);
            }
        }
        return connect;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel bt_close;
    private javax.swing.JLabel home;
    private javax.swing.JPasswordField pw;
    private javax.swing.JLabel signin;
    private javax.swing.JTextField usernm;
    // End of variables declaration//GEN-END:variables
}
