/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Halaman;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author BintangDiLangit
 */
public class menu_admin extends javax.swing.JFrame {

    /**
     * Creates new form tambahData
     */
    public menu_admin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        arta = new javax.swing.JLabel();
        tambahdata = new javax.swing.JLabel();
        cariedit = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        arta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                artaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                artaMouseExited(evt);
            }
        });
        getContentPane().add(arta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 340, 40));

        tambahdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahdataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tambahdataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tambahdataMouseExited(evt);
            }
        });
        getContentPane().add(tambahdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 170, 170));

        cariedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carieditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carieditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carieditMouseExited(evt);
            }
        });
        getContentPane().add(cariedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 170, 170));

        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minMouseExited(evt);
            }
        });
        getContentPane().add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 60, 40));

        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 60, 40));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Halaman/gambar/ma.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseEntered
        ImageIcon L=new ImageIcon (getClass().getResource("gambar/mamin.jpg"));
        bg.setIcon(L);
    }//GEN-LAST:event_minMouseEntered

    private void minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseExited
        ImageIcon L=new ImageIcon (getClass().getResource("gambar/ma.jpg"));
        bg.setIcon(L);
    }//GEN-LAST:event_minMouseExited

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        ImageIcon L=new ImageIcon (getClass().getResource("gambar/maclose.jpg"));
        bg.setIcon(L);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        ImageIcon L=new ImageIcon (getClass().getResource("gambar/ma.jpg"));
        bg.setIcon(L);
    }//GEN-LAST:event_closeMouseExited

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        loginadmin M = new loginadmin();
        M.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        ImageIcon L=new ImageIcon (getClass().getResource("gambar/malogout.jpg"));
        bg.setIcon(L);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        ImageIcon L=new ImageIcon (getClass().getResource("gambar/ma.jpg"));
        bg.setIcon(L);
    }//GEN-LAST:event_logoutMouseExited

    private void carieditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carieditMouseClicked
        cariedit_admin C = new cariedit_admin();
        C.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_carieditMouseClicked

    private void carieditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carieditMouseEntered
        ImageIcon L=new ImageIcon (getClass().getResource("gambar/macariedit.jpg"));
        bg.setIcon(L);
    }//GEN-LAST:event_carieditMouseEntered

    private void carieditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carieditMouseExited
        ImageIcon L=new ImageIcon (getClass().getResource("gambar/ma.jpg"));
        bg.setIcon(L);
    }//GEN-LAST:event_carieditMouseExited

    private void tambahdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahdataMouseClicked
        tambah_data M = new tambah_data();
        M.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tambahdataMouseClicked

    private void tambahdataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahdataMouseEntered
        ImageIcon L=new ImageIcon (getClass().getResource("gambar/matambah.jpg"));
        bg.setIcon(L);
    }//GEN-LAST:event_tambahdataMouseEntered

    private void tambahdataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahdataMouseExited
        ImageIcon L=new ImageIcon (getClass().getResource("gambar/ma.jpg"));
        bg.setIcon(L);
    }//GEN-LAST:event_tambahdataMouseExited

    private void artaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_artaMouseEntered
        ImageIcon L=new ImageIcon (getClass().getResource("gambar/ma2.jpg"));
        bg.setIcon(L);
    }//GEN-LAST:event_artaMouseEntered

    private void artaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_artaMouseExited
        ImageIcon L=new ImageIcon (getClass().getResource("gambar/ma.jpg"));
        bg.setIcon(L);
    }//GEN-LAST:event_artaMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arta;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel cariedit;
    private javax.swing.JLabel close;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel min;
    private javax.swing.JLabel tambahdata;
    // End of variables declaration//GEN-END:variables
}
