/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Halaman;

import java.awt.Color;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author AFRIZAL'R
 */
public class orderUser extends javax.swing.JFrame {

    private int size;
    private String tot;
//    private String date;

    //Struktur data
    DataArray arr;
    Tree theTree;
    HashTable hash;

    CRUD cr = new CRUD();

    /**
     * Creates new form laman
     */
    public orderUser() {
        initComponents();
        this.setLocationRelativeTo(null);
        txt_nama.setBackground(new Color(0, 0, 0, 0));
        txt_alamat.setBackground(new Color(0, 0, 0, 0));
        txt_jmlorang.setBackground(new Color(0, 0, 0, 0));
        txt_nohp.setBackground(new Color(0, 0, 0, 0));
        bali.setBackground(Color.black);
//        bndung.setBackground(Color.black);
//        jogja.setBackground(Color.black);

        size = 2 ^ 30;
        arr = new DataArray(size);
        theTree = new Tree();
        hash = new HashTable(size);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttongrp = new javax.swing.ButtonGroup();
        txt_jmlorang = new javax.swing.JComboBox<>();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        bali = new javax.swing.JRadioButton();
        bndung = new javax.swing.JRadioButton();
        jogja = new javax.swing.JRadioButton();
        btkembali = new javax.swing.JLabel();
        btnmin = new javax.swing.JLabel();
        btnclose = new javax.swing.JLabel();
        btnpesan = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        txt_nohp = new javax.swing.JTextField();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 550));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_jmlorang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "50", "100", "150", "200", "250", "300", "+300" }));
        getContentPane().add(txt_jmlorang, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 260, -1));
        getContentPane().add(jCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 430, 130));

        bali.setBackground(new java.awt.Color(0, 0, 0));
        buttongrp.add(bali);
        bali.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        bali.setText("Bali");
        getContentPane().add(bali, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, 20));

        bndung.setBackground(new java.awt.Color(0, 0, 0));
        buttongrp.add(bndung);
        bndung.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        bndung.setText("Bandung");
        getContentPane().add(bndung, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, 20));

        jogja.setBackground(new java.awt.Color(0, 0, 0));
        buttongrp.add(jogja);
        jogja.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jogja.setText("Yogyakarta");
        getContentPane().add(jogja, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, 20));

        btkembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btkembaliMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btkembaliMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btkembaliMouseEntered(evt);
            }
        });
        getContentPane().add(btkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 170, 40));

        btnmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnminMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnminMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnminMouseEntered(evt);
            }
        });
        getContentPane().add(btnmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 30, 30));

        btnclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncloseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncloseMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncloseMouseEntered(evt);
            }
        });
        getContentPane().add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 40, 30));

        btnpesan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpesanMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnpesanMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnpesanMouseEntered(evt);
            }
        });
        getContentPane().add(btnpesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 170, 50));

        txt_nama.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 260, 30));

        txt_alamat.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txt_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alamatActionPerformed(evt);
            }
        });
        getContentPane().add(txt_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 260, 30));

        txt_nohp.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(txt_nohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 260, 30));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Halaman/gambar3/ou.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatActionPerformed

    private void btnpesanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpesanMouseClicked

        
        double bl = 95;
        double bd = 130;
        double jg = 125;
        double cost = 0;
        
     
    
        if (txt_jmlorang.getSelectedItem().equals("50")&&bali.isSelected()) {
            cost= bl;      
            
            String total = String.format("Rp.%.2f", cost);
            JOptionPane.showMessageDialog(null, "Total Biaya"+"\n"+ total+" juta"+"\n"+"segera lunasi pembayaran\nBRI Rek.732487834223");
        }else if(txt_jmlorang.getSelectedItem().equals("100")&&bali.isSelected()){
            cost= bl*2;  
            String total = String.format("Rp.%.2f", cost);
            JOptionPane.showMessageDialog(null, "Total Biaya"+"\n"+ total+" juta"+"\n"+"segera lunasi pembayaran\nBRI Rek.732487834223");
        }else if(txt_jmlorang.getSelectedItem().equals("150")&&bali.isSelected()){
            cost= bl*3;  
            String total = String.format("Rp.%.2f", cost);
            JOptionPane.showMessageDialog(null, "Total Biaya"+"\n"+ total+" juta"+"\n"+"segera lunasi pembayaran\nBRI Rek.732487834223");
        }else if(txt_jmlorang.getSelectedItem().equals("200")&&bali.isSelected()){
            cost= bl*4;  
            String total = String.format("Rp.%.2f", cost);
            JOptionPane.showMessageDialog(null, "Total Biaya"+"\n"+ total+" juta"+"\n"+"segera lunasi pembayaran\nBRI Rek.732487834223");
        }else if(txt_jmlorang.getSelectedItem().equals("250")&&bali.isSelected()){
            cost= bl*5;  
            String total = String.format("Rp.%.2f", cost);
            JOptionPane.showMessageDialog(null, "Total Biaya"+"\n"+ total+" juta"+"\n"+"segera lunasi pembayaran\nBRI Rek.732487834223");
        }else if(txt_jmlorang.getSelectedItem().equals("300")&&bali.isSelected()){
            cost= bl*6;  
            String total = String.format("Rp.%.2f", cost);
            JOptionPane.showMessageDialog(null, "Total Biaya"+"\n"+ total+" juta"+"\n"+"segera lunasi pembayaran\nBRI Rek.732487834223");
        }else if(txt_jmlorang.getSelectedItem().equals("+300")&&bali.isSelected()){
            cost= bl*10;  
            String total = String.format("Rp.%.2f", cost);
            JOptionPane.showMessageDialog(null, "Total Biaya"+"\n"+ total+" juta"+"\n"+"segera lunasi pembayaran\nBRI Rek.732487834223");
        }else if(txt_jmlorang.getSelectedItem().equals("50")&&bndung.isSelected()){
            cost= bd;  
            String total = String.format("Rp.%.2f", cost);
            JOptionPane.showMessageDialog(null, "Total Biaya"+"\n"+ total+" juta"+"\n"+"segera lunasi pembayaran\nBRI Rek.732487834223");
        }else if(txt_jmlorang.getSelectedItem().equals("100")&&bndung.isSelected()){
            cost= bd*2;  
            String total = String.format("Rp.%.2f", cost);
            JOptionPane.showMessageDialog(null, "Total Biaya"+"\n"+ total+" juta"+"\n"+"segera lunasi pembayaran\nBRI Rek.732487834223");
        }else if(txt_jmlorang.getSelectedItem().equals("150")&&bndung.isSelected()){
            cost= bd*3;  
            String total = String.format("Rp.%.2f", cost);
            JOptionPane.showMessageDialog(null, "Total Biaya"+"\n"+ total+" juta"+"\n"+"segera lunasi pembayaran\nBRI Rek.732487834223");
        }else if(txt_jmlorang.getSelectedItem().equals("200")&&bndung.isSelected()){
            cost= bd*4;  
            String total = String.format("Rp.%.2f", cost);
            JOptionPane.showMessageDialog(null, "Total Biaya"+"\n"+ total+" juta"+"\n"+"segera lunasi pembayaran\nBRI Rek.732487834223");
        }else if(txt_jmlorang.getSelectedItem().equals("250")&&bndung.isSelected()){
            cost= bd*5;  
            String total = String.format("Rp.%.2f", cost);
            JOptionPane.showMessageDialog(null, "Total Biaya"+"\n"+ total+" juta"+"\n"+"segera lunasi pembayaran\nBRI Rek.732487834223");
        }else if(txt_jmlorang.getSelectedItem().equals("300")&&bndung.isSelected()){
            cost= bd*6;  
            String total = String.format("Rp.%.2f", cost);
            JOptionPane.showMessageDialog(null, "Total Biaya"+"\n"+ total+" juta"+"\n"+"segera lunasi pembayaran\nBRI Rek.732487834223");
        }else if(txt_jmlorang.getSelectedItem().equals("+300")&&bndung.isSelected()){
            cost= bd*10;  
            String total = String.format("Rp.%.2f", cost);
            JOptionPane.showMessageDialog(null, "Total Biaya"+"\n"+ total+" juta"+"\n"+"segera lunasi pembayaran\nBRI Rek.732487834223");
        }else if(txt_jmlorang.getSelectedItem().equals("50")&&jogja.isSelected()){
            cost= jg*1;  
            String total = String.format("Rp.%.2f", cost);
            JOptionPane.showMessageDialog(null, "Total Biaya"+"\n"+ total+" juta"+"\n"+"segera lunasi pembayaran\nBRI Rek.732487834223");
        }else if(txt_jmlorang.getSelectedItem().equals("100")&&jogja.isSelected()){
            cost= jg*2;  
            String total = String.format("Rp.%.2f", cost);
            JOptionPane.showMessageDialog(null, "Total Biaya"+"\n"+ total+" juta"+"\n"+"segera lunasi pembayaran\nBRI Rek.732487834223");
        }else if(txt_jmlorang.getSelectedItem().equals("150")&&jogja.isSelected()){
            cost= jg*3;  
            String total = String.format("Rp.%.2f", cost);
            JOptionPane.showMessageDialog(null, "Total Biaya"+"\n"+ total+" juta"+"\n"+"segera lunasi pembayaran\nBRI Rek.732487834223");
        }else if(txt_jmlorang.getSelectedItem().equals("200")&&jogja.isSelected()){
            cost= jg*4;  
            String total = String.format("Rp.%.2f", cost);
            JOptionPane.showMessageDialog(null, "Total Biaya"+"\n"+ total+" juta"+"\n"+"segera lunasi pembayaran\nBRI Rek.732487834223");
        }else if(txt_jmlorang.getSelectedItem().equals("250")&&jogja.isSelected()){
            cost= jg*5;  
            String total = String.format("Rp.%.2f", cost);
            JOptionPane.showMessageDialog(null, "Total Biaya"+"\n"+ total+" juta"+"\n"+"segera lunasi pembayaran\nBRI Rek.732487834223");
        }else if(txt_jmlorang.getSelectedItem().equals("300")&&jogja.isSelected()){
            cost= jg*6;  
            String total = String.format("Rp.%.2f", cost);
            JOptionPane.showMessageDialog(null, "Total Biaya"+"\n"+ total+" juta"+"\n"+"segera lunasi pembayaran\nBRI Rek.732487834223");
        }else if(txt_jmlorang.getSelectedItem().equals("+300")&&jogja.isSelected()){
            cost= jg*7;  
            String total = String.format("Rp.%.2f", cost);
            JOptionPane.showMessageDialog(null, "Total Biaya"+"\n"+ total+" juta"+"\n"+"segera lunasi pembayaran\nBRI Rek.732487834223");
        }
//        else if(txt_jmlorang.getSelectedItem().equals("0")){
//            JOptionPane.showMessageDialog(null, "Mohon Lengkapi Data");
//        }else{
//            JOptionPane.showMessageDialog(null, "Mohon Lengkapi Data");
//        }
        tot = Double.toString(cost);
        
        
//        if (bali.isSelected()) {
//            rincian.setText("Transfer BRI, No. Rek.");
//            rincian1.setText("732487834223");
//            rincian2.setText("Rp." + biayabali);
//
//        } else if (bndung.isSelected()) {
//            rincian.setText("Transfer BNI No. Rek.");
//            rincian1.setText("523432434111");
//            rincian2.setText("Rp." + biayabndng);
//        } else if (jogja.isSelected()) {
//            rincian.setText("Transfer BCA No. Rek.");
//            rincian1.setText("332000i34223");
//            rincian2.setText("Rp." + biayajogja);
//        }

        tambahOrder();
        
        
        
        
//        String biayabali = "95Jt";
//        String biayabndng = "130Jt";
//        String biayajogja = "125Jt";
//
//        if (bali.isSelected()) {
//            JOptionPane.showMessageDialog(null, "Total Biaya"+"\n" +"Rp."+ biayabali+"\n"+"segera lunasi pembayaran\nBRI Rek.732487834223");
//        } else if (bndung.isSelected()) {
//            JOptionPane.showMessageDialog(null, "Total Biaya"+"\n" +"Rp."+ biayabndng+"\n"+"segera lunasi pembayaran\nBNI Rek.523432434111");
//        } else if (jogja.isSelected()) {
//            JOptionPane.showMessageDialog(null, "Total Biaya"+"\n" +"Rp."+ biayajogja+"\n"+"segera lunasi pembayaran\nBCA Rek.332000i34223");
//        }
//        try {
//            tambahOrder();
//            popupSimpanuser P = new popupSimpanuser();
//            P.setVisible(true);
//
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_btnpesanMouseClicked

    private void btnminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnminMouseClicked
        this.setState(JFrame.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_btnminMouseClicked

    private void btnminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnminMouseEntered
        ImageIcon L = new ImageIcon(getClass().getResource("gambar3/mumin.jpg"));
        bg.setIcon(L);
    }//GEN-LAST:event_btnminMouseEntered

    private void btnminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnminMouseExited
        ImageIcon L = new ImageIcon(getClass().getResource("gambar3/ou.jpg"));
        bg.setIcon(L);
    }//GEN-LAST:event_btnminMouseExited

    private void btncloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseClicked
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_btncloseMouseClicked

    private void btncloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseEntered
        ImageIcon L = new ImageIcon(getClass().getResource("gambar3/muclose.jpg"));
        bg.setIcon(L);
    }//GEN-LAST:event_btncloseMouseEntered

    private void btncloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseExited
        ImageIcon L = new ImageIcon(getClass().getResource("gambar3/ou.jpg"));
        bg.setIcon(L);
    }//GEN-LAST:event_btncloseMouseExited

    private void btnpesanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpesanMouseEntered
        ImageIcon L = new ImageIcon(getClass().getResource("gambar3/mupesan.jpg"));
        bg.setIcon(L);
    }//GEN-LAST:event_btnpesanMouseEntered

    private void btnpesanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpesanMouseExited
        ImageIcon L = new ImageIcon(getClass().getResource("gambar3/ou.jpg"));
        bg.setIcon(L);
    }//GEN-LAST:event_btnpesanMouseExited

    private void btkembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btkembaliMouseClicked
        menu_user M = new menu_user();
        M.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btkembaliMouseClicked

    private void btkembaliMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btkembaliMouseEntered
        ImageIcon L = new ImageIcon(getClass().getResource("gambar3/mumenu.jpg"));
        bg.setIcon(L);
    }//GEN-LAST:event_btkembaliMouseEntered

    private void btkembaliMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btkembaliMouseExited
        ImageIcon L = new ImageIcon(getClass().getResource("gambar3/ou.jpg"));
        bg.setIcon(L);
    }//GEN-LAST:event_btkembaliMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(orderUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(orderUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(orderUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(orderUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new orderUser().setVisible(true);
            }
        });
    }

    private void tambahOrder() {
//        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String tgl = dateFormat.format(jCalendar1.getDate());
//        Date newDate = new Date();
//        System.out.println(dateFormat.format(newDate));
//        String pattern = "dd-MM-yyyy";
//        DateFormat formatter = new SimpleDateFormat(pattern);

        String paket = "";
        if (bali.isSelected()) {
            paket = bali.getText();
        } else if (bndung.isSelected()) {
            paket = bndung.getText();
        } else if (jogja.isSelected()){
            paket = jogja.getText();
        }
//        System.out.println(jDate);

//        String date =txt_date.getText();
        String nama = txt_nama.getText();
        String alamat = txt_alamat.getText();
        String nohp = txt_nohp.getText();
        String jmlorang = txt_jmlorang.getSelectedItem().toString();
        if (!txt_nama.getText().equals("") && !txt_alamat.getText().equals("") && !txt_nohp.getText().equals("") && paket!=null && jmlorang!="0"&& !jCalendar1.equals("")) {
            try {
                    cr.tambahData(nama, alamat, nohp, paket, jmlorang, tgl,tot);
                
                txt_nama.setText("");
                txt_alamat.setText("");
                txt_nohp.setText("");
                txt_jmlorang.setSelectedItem("0");
                buttongrp.clearSelection();
//                jCalendar1.isNullDateButtonVisible();

                int id = cr.getLastID();
                add(id, nama, alamat, nohp, paket, jmlorang, tgl,tot);

            } catch (Exception e) {
                System.out.println("ERROOORR!!!");
                System.out.println(e);
                e.printStackTrace();

            }
        }else{
            JOptionPane.showMessageDialog(null, "Data Belum Tersimpan"+"\nMohon Lengkapi Data");
        }

    }

    private void add(int id, String nama, String alamat, String nohp, String paket, String jmlorang, String tgl,String tot) {
        arr.insert(id, nama, alamat, nohp, paket, jmlorang, tgl,tot);
        theTree.insert(id, nama, alamat, nohp, paket, jmlorang, tgl,tot);
        hash.put(id, nama, alamat, nohp, paket, jmlorang, tgl,tot);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bali;
    private javax.swing.JLabel bg;
    private javax.swing.JRadioButton bndung;
    private javax.swing.JLabel btkembali;
    private javax.swing.JLabel btnclose;
    private javax.swing.JLabel btnmin;
    private javax.swing.JLabel btnpesan;
    private javax.swing.ButtonGroup buttongrp;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JRadioButton jogja;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JComboBox<String> txt_jmlorang;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nohp;
    // End of variables declaration//GEN-END:variables
}
