/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Halaman;

import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author BintangDiLangit
 */
public class tambah_data extends javax.swing.JFrame {

    private int size;
//    private String date;
    private String tot;
    //Struktur data
    DataArray arr;
    Tree theTree;
    HashTable hash;
    Travel trav;

    CRUD cr = new CRUD();

    /**
     * Creates new form menu_admin
     */
    public tambah_data() {
        initComponents();
        this.setLocationRelativeTo(null);
        txt_nama.setBackground(new Color(0, 0, 0, 0));
        txt_alamat.setBackground(new Color(0, 0, 0, 0));
        txt_jmlorang.setBackground(new Color(0, 0, 0, 0));
        txt_nohp.setBackground(new Color(0, 0, 0, 0));

        size = 2 ^ 30;
        arr = new DataArray(size);
        theTree = new Tree();
        hash = new HashTable(size);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttongrp = new javax.swing.ButtonGroup();
        txt_jmlorang = new javax.swing.JComboBox<>();
        rincian2 = new javax.swing.JTextField();
        rincian1 = new javax.swing.JTextField();
        rincian = new javax.swing.JTextField();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        txt_nama = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        txt_nohp = new javax.swing.JTextField();
        jogja = new javax.swing.JRadioButton();
        bndung = new javax.swing.JRadioButton();
        bali = new javax.swing.JRadioButton();
        pesan = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        menuawl = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_jmlorang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "50", "100", "150", "200", "250", "300", "+300" }));
        getContentPane().add(txt_jmlorang, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 330, -1));

        rincian2.setEnabled(false);
        getContentPane().add(rincian2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, 230, 30));

        rincian1.setEnabled(false);
        getContentPane().add(rincian1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 230, 30));

        rincian.setEnabled(false);
        getContentPane().add(rincian, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, 230, 30));
        getContentPane().add(jCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 420, 120));

        txt_nama.setBackground(null);
        txt_nama.setForeground(new java.awt.Color(0, 0, 0));
        txt_nama.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        txt_nama.setCaretColor(new java.awt.Color(0, 0, 0));
        txt_nama.setOpaque(false);
        getContentPane().add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 330, 50));

        txt_alamat.setBackground(null);
        txt_alamat.setForeground(new java.awt.Color(0, 0, 0));
        txt_alamat.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        txt_alamat.setCaretColor(new java.awt.Color(0, 0, 0));
        txt_alamat.setOpaque(false);
        getContentPane().add(txt_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 330, 50));

        txt_nohp.setBackground(null);
        txt_nohp.setForeground(new java.awt.Color(0, 0, 0));
        txt_nohp.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        txt_nohp.setCaretColor(new java.awt.Color(0, 0, 0));
        txt_nohp.setOpaque(false);
        txt_nohp.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                txt_nohpVetoableChange(evt);
            }
        });
        getContentPane().add(txt_nohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 330, 50));

        buttongrp.add(jogja);
        jogja.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jogja.setText("Yogyakarta");
        getContentPane().add(jogja, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, -1, 40));

        buttongrp.add(bndung);
        bndung.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        bndung.setText("Bandung");
        getContentPane().add(bndung, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, 40));

        buttongrp.add(bali);
        bali.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        bali.setText("Bali");
        getContentPane().add(bali, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, 40));

        pesan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesanMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pesanMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pesanMouseEntered(evt);
            }
        });
        getContentPane().add(pesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 110, 40));

        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minMouseEntered(evt);
            }
        });
        getContentPane().add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 60, 40));

        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 60, 40));

        menuawl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuawlMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuawlMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuawlMouseEntered(evt);
            }
        });
        getContentPane().add(menuawl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Halaman/gambar/td.jpg"))); // NOI18N
        bg.setOpaque(false);
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuawlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuawlMouseEntered
        ImageIcon L = new ImageIcon(getClass().getResource("gambar/tdmenu.jpg"));
        bg.setIcon(L);
    }//GEN-LAST:event_menuawlMouseEntered

    private void menuawlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuawlMouseExited
        ImageIcon L = new ImageIcon(getClass().getResource("gambar/td.jpg"));
        bg.setIcon(L);
    }//GEN-LAST:event_menuawlMouseExited

    private void menuawlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuawlMouseClicked
        menu_admin M = new menu_admin();
        M.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuawlMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        ImageIcon L = new ImageIcon(getClass().getResource("gambar/tdclose.jpg"));
        bg.setIcon(L);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        ImageIcon L = new ImageIcon(getClass().getResource("gambar/td.jpg"));
        bg.setIcon(L);
    }//GEN-LAST:event_closeMouseExited

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseEntered
        ImageIcon L = new ImageIcon(getClass().getResource("gambar/tdmin.jpg"));
        bg.setIcon(L);
    }//GEN-LAST:event_minMouseEntered

    private void minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseExited
        ImageIcon L = new ImageIcon(getClass().getResource("gambar/td.jpg"));
        bg.setIcon(L);
    }//GEN-LAST:event_minMouseExited

    private void pesanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesanMouseClicked

        double bl = 95;
        double bd = 130;
        double jg = 125;
        double cost = 0;
        
     
    
        if (txt_jmlorang.getSelectedItem().equals("50")&&bali.isSelected()) {
            cost= bl;      
            
            String total = String.format("Rp.%.2f", cost);
            rincian.setText(total+" juta");
            rincian1.setText("732487834223");
            rincian2.setText("Transfer BNI No. Rek.");
        }else if(txt_jmlorang.getSelectedItem().equals("100")&&bali.isSelected()){
            cost= bl*2;  
            String total = String.format("Rp.%.2f", cost);
            rincian.setText(total+" juta");
            rincian1.setText("732487834223");
            rincian2.setText("Transfer BNI No. Rek.");
        }else if(txt_jmlorang.getSelectedItem().equals("150")&&bali.isSelected()){
            cost= bl*3;  
            String total = String.format("Rp.%.2f", cost);
            rincian.setText(total+" juta");
            rincian1.setText("732487834223");
            rincian2.setText("Transfer BNI No. Rek.");
        }else if(txt_jmlorang.getSelectedItem().equals("200")&&bali.isSelected()){
            cost= bl*4;  
            String total = String.format("Rp.%.2f", cost);
            rincian.setText(total+" juta");
            rincian1.setText("732487834223");
            rincian2.setText("Transfer BNI No. Rek.");
        }else if(txt_jmlorang.getSelectedItem().equals("250")&&bali.isSelected()){
            cost= bl*5;  
            String total = String.format("Rp.%.2f", cost);
            rincian.setText(total+" juta");
            rincian1.setText("732487834223");
            rincian2.setText("Transfer BNI No. Rek.");
        }else if(txt_jmlorang.getSelectedItem().equals("300")&&bali.isSelected()){
            cost= bl*6;  
            String total = String.format("Rp.%.2f", cost);
            rincian.setText(total+" juta");
            rincian1.setText("732487834223");
            rincian2.setText("Transfer BNI No. Rek.");
        }else if(txt_jmlorang.getSelectedItem().equals("+300")&&bali.isSelected()){
            cost= bl*10;  
            String total = String.format("Rp.%.2f", cost);
            rincian.setText(total+" juta");
            rincian1.setText("732487834223");
            rincian2.setText("Transfer BNI No. Rek.");
        }else if(txt_jmlorang.getSelectedItem().equals("50")&&bndung.isSelected()){
            cost= bd;  
            String total = String.format("Rp.%.2f", cost);
            rincian.setText(total+" juta");
            rincian1.setText("732487834223");
            rincian2.setText("Transfer BNI No. Rek.");
        }else if(txt_jmlorang.getSelectedItem().equals("100")&&bndung.isSelected()){
            cost= bd*2;  
            String total = String.format("Rp.%.2f", cost);
            rincian.setText(total+" juta");
            rincian1.setText("732487834223");
            rincian2.setText("Transfer BNI No. Rek.");
        }else if(txt_jmlorang.getSelectedItem().equals("150")&&bndung.isSelected()){
            cost= bd*3;  
            String total = String.format("Rp.%.2f", cost);
            rincian.setText(total+" juta");
            rincian1.setText("732487834223");
            rincian2.setText("Transfer BNI No. Rek.");
        }else if(txt_jmlorang.getSelectedItem().equals("200")&&bndung.isSelected()){
            cost= bd*4;  
            String total = String.format("Rp.%.2f", cost);
            rincian.setText(total+" juta");
            rincian1.setText("732487834223");
            rincian2.setText("Transfer BNI No. Rek.");
        }else if(txt_jmlorang.getSelectedItem().equals("250")&&bndung.isSelected()){
            cost= bd*5;  
            String total = String.format("Rp.%.2f", cost);
            rincian.setText(total+" juta");
            rincian1.setText("732487834223");
            rincian2.setText("Transfer BNI No. Rek.");
        }else if(txt_jmlorang.getSelectedItem().equals("300")&&bndung.isSelected()){
            cost= bd*6;  
            String total = String.format("Rp.%.2f", cost);
            rincian.setText(total+" juta");
            rincian1.setText("732487834223");
            rincian2.setText("Transfer BNI No. Rek.");
        }else if(txt_jmlorang.getSelectedItem().equals("+300")&&bndung.isSelected()){
            cost= bd*10;  
            String total = String.format("Rp.%.2f", cost);
            rincian.setText(total+" juta");
            rincian1.setText("732487834223");
            rincian2.setText("Transfer BNI No. Rek.");
        }else if(txt_jmlorang.getSelectedItem().equals("50")&&jogja.isSelected()){
            cost= jg*1;  
            String total = String.format("Rp.%.2f", cost);
            rincian.setText(total+" juta");
            rincian1.setText("732487834223");
            rincian2.setText("Transfer BNI No. Rek.");
        }else if(txt_jmlorang.getSelectedItem().equals("100")&&jogja.isSelected()){
            cost= jg*2;  
            String total = String.format("Rp.%.2f", cost);
            rincian.setText(total+" juta");
            rincian1.setText("732487834223");
            rincian2.setText("Transfer BNI No. Rek.");
        }else if(txt_jmlorang.getSelectedItem().equals("150")&&jogja.isSelected()){
            cost= jg*3;  
            String total = String.format("Rp.%.2f", cost);
            rincian.setText(total+" juta");
            rincian1.setText("732487834223");
            rincian2.setText("Transfer BNI No. Rek.");
        }else if(txt_jmlorang.getSelectedItem().equals("200")&&jogja.isSelected()){
            cost= jg*4;  
            String total = String.format("Rp.%.2f", cost);
            rincian.setText(total+" juta");
            rincian1.setText("732487834223");
            rincian2.setText("Transfer BNI No. Rek.");
        }else if(txt_jmlorang.getSelectedItem().equals("250")&&jogja.isSelected()){
            cost= jg*5;  
            String total = String.format("Rp.%.2f", cost);
            rincian.setText(total+" juta");
            rincian1.setText("732487834223");
            rincian2.setText("Transfer BNI No. Rek.");
        }else if(txt_jmlorang.getSelectedItem().equals("300")&&jogja.isSelected()){
            cost= jg*6;  
            String total = String.format("Rp.%.2f", cost);
            rincian.setText(total+" juta");
            rincian1.setText("732487834223");
            rincian2.setText("Transfer BNI No. Rek.");
        }else if(txt_jmlorang.getSelectedItem().equals("+300")&&jogja.isSelected()){
            cost= jg*7;  
            String total = String.format("Rp.%.2f", cost);
            rincian.setText(total+" juta");
            rincian1.setText("732487834223");
            rincian2.setText("Transfer BNI No. Rek.");
        }
//        else if(txt_jmlorang.getSelectedItem().equals("0")){
//            JOptionPane.showMessageDialog(null, "Mohon Lengkapi Data");
//        }else{
//            JOptionPane.showMessageDialog(null, "Mohon Lengkapi Data");
//        }
        tot = Double.toString(cost);
        
        
//        if (bali.isSelected()) {
//            rincian.setText("Transfer BRI, No. Rek.");
//            rincian1.setText("732487834223");
//            rincian2.setText("Rp." + biayabali);
//
//        } else if (bndung.isSelected()) {
//            rincian.setText("Transfer BNI No. Rek.");
//            rincian1.setText("523432434111");
//            rincian2.setText("Rp." + biayabndng);
//        } else if (jogja.isSelected()) {
//            rincian.setText("Transfer BCA No. Rek.");
//            rincian1.setText("332000i34223");
//            rincian2.setText("Rp." + biayajogja);
//        }

        tambahOrder();
//        popupSimpan P = new popupSimpan();
//        P.setVisible(true);
//        this.setVisible(false);


    }//GEN-LAST:event_pesanMouseClicked

    private void pesanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesanMouseEntered
        ImageIcon L = new ImageIcon(getClass().getResource("gambar/tdpesan.jpg"));
        bg.setIcon(L);
    }//GEN-LAST:event_pesanMouseEntered

    private void pesanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesanMouseExited
        ImageIcon L = new ImageIcon(getClass().getResource("gambar/td.jpg"));
        bg.setIcon(L);
    }//GEN-LAST:event_pesanMouseExited

    private void txt_nohpVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_txt_nohpVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nohpVetoableChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambah_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambah_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambah_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambah_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambah_data().setVisible(true);
            }
        });

    }

    private void tambahOrder() {
//        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String tgl = dateFormat.format(jCalendar1.getDate());
//        Date newDate = new Date();
//        System.out.println(dateFormat.format(newDate));
//        String pattern = "dd-MM-yyyy";
//        DateFormat formatter = new SimpleDateFormat(pattern);

        String paket = "";
        if (bali.isSelected()) {
            paket = bali.getText();
        } else if (bndung.isSelected()) {
            paket = bndung.getText();
        } else if (jogja.isSelected()){
            paket = jogja.getText();
        }
//        System.out.println(jDate);

//        String date =txt_date.getText();
        String nama = txt_nama.getText();
        String alamat = txt_alamat.getText();
        String nohp = txt_nohp.getText();
        String jmlorang = txt_jmlorang.getSelectedItem().toString();
        if (!txt_nama.getText().equals("") && !txt_alamat.getText().equals("")
                && !txt_nohp.getText().equals("") && !jCalendar1.equals("") 
                && paket!=null && jmlorang!="0") {
            try {
                    cr.tambahData(nama, alamat, nohp, paket, jmlorang, tgl,tot);
                txt_nama.setText("");
                txt_alamat.setText("");
                txt_nohp.setText("");
                txt_jmlorang.setSelectedItem("0");
                buttongrp.clearSelection();
//                jCalendar1.isNullDateButtonVisible();

                int id = cr.getLastID();
                add(id, nama, alamat, nohp, paket, jmlorang, tgl,tot);
                
            } catch (Exception e) {
                System.out.println("ERROOORR!!!");
                System.out.println(e);
                e.printStackTrace();

            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Data Belum Tersimpan"+"\nMohon Lengkapi Data");
        }

    }

    private void add(int id, String nama, String alamat, String nohp, String paket, String jmlorang, String tgl,String tot) {
        arr.insert(id, nama, alamat, nohp, paket, jmlorang, tgl,tot);
        theTree.insert(id, nama, alamat, nohp, paket, jmlorang, tgl,tot);
        hash.put(id, nama, alamat, nohp, paket, jmlorang, tgl,tot);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bali;
    private javax.swing.JLabel bg;
    private javax.swing.JRadioButton bndung;
    private javax.swing.ButtonGroup buttongrp;
    private javax.swing.JLabel close;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JRadioButton jogja;
    private javax.swing.JLabel menuawl;
    private javax.swing.JLabel min;
    private javax.swing.JLabel pesan;
    private javax.swing.JTextField rincian;
    private javax.swing.JTextField rincian1;
    private javax.swing.JTextField rincian2;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JComboBox<String> txt_jmlorang;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nohp;
    // End of variables declaration//GEN-END:variables
}
